return {
	[0] = 'The Ronfaure Region',
	[1] = 'The Zulkheim Region',
	[2] = 'The Norvallen Region',
	[3] = 'The Gustaberg Region',
	[4] = 'The Derfland Region',
	[5] = 'The Sarutabaruta Region',
	[6] = 'The Kolshushu Region',
	[7] = 'The Aragoneu Region',
	[8] = 'The Fauregandi Region',
	[9] = 'The Valdeaunia Region',
	[10] = 'Qufim Island',
	[11] = 'The Li\'Telor Region',
	[12] = 'The Kuzotz Region',
	[13] = 'The Vollbow Region',
	[14] = 'The Elshimo Lowlands Region',
	[15] = 'The Elshimo Uplands Region',
	[16] = 'Tu\'Lia',
	--[17] = 'Movapolos',
	[18] = 'The Tavnazian Archipelago',
}